feat(#72): test-object-is-not-verb-in-singular lint
objectionary/lints pull request #103
Opened 2024-12-05 18:22 UTC by h1alexbel

In this pull I've introduced new lint: `test-object-is-not-verb-in-singular`, that issues `warning` in case of test object name doesn't start with verb in singular form:

```
this-is-test, isItTrue, run-test -> warning
```

```
runs, prints-data, works-as-expected, parses-dom -> passes
```

closes #72
History:
- **feat(#72): select first**
- **feat(#72): test packs**
- **feat(#72): in java**
- **feat(#72): opennlp**
- **feat(#72): check tags**
- **feat(#72): add defect**
- **feat(#72): test cases**
- **feat(#72): yamls off**
- **feat(#72): up**
- **feat(#72): motive**
- **feat(#72): package-info**
- **feat(#72): puzzle**
- **feat(#72): URI**
- **feat(#72): clean for qulice**

2024-12-05 18:40 UTC, h1alexbel commented
@yegor256 take a look, please

2024-12-06 15:37 UTC, h1alexbel commented
@volodya-lombrozo reminder

2024-12-08 11:24 UTC, h1alexbel commented
@volodya-lombrozo reminder

2024-12-09 08:22 UTC, volodya-lombrozo requested changes
@h1alexbel Thank you for the contribution! The PR looks pretty well. Just a few small suggestions.

2024-12-09 08:22 UTC, volodya-lombrozo commented on src/test/java/org/eolang/lints/misc/TestObjectIsVerbInSingularTest.java
> +        TestObjectIsVerbInSingularTest.model = new POSTaggerME(
@h1alexbel [NIT] You might use the default constructor `public TestObjectIsVerbInSingular()` here instead, am I right?

2024-12-09 08:22 UTC, volodya-lombrozo commented on src/test/resources/org/eolang/lints/misc/test-object-is-not-verb-in-singular/bad/itIsTrue.eo
> ++tests
@h1alexbel [Opinionated] You have a separate file for each test case. It's more or less fine, but due to the license text, it looks a bit verbose. Is it possible (worth it) to put all the test cases into a single file? Moreover, here you test only a few of examples. What about the following test cases:

```eo
# Tricky Test Names
+tests

# Foo.
[] > breaks-hearts
  42 > @

[] > it-works
  42 > @

[] > nothing-happened
  42 > @

[] > has-been-found
  42 > @

[] > something-is-wrong
  42 > @

[] > crashes-again
  42 > @

[] > will-fail-eventually
  42 > @

[] > always-returns-true
  42 > @

[] > was-lost-forever
  42 > @

[] > is-almost-correct
  42 > @

[] > nobody-knows-why
  42 > @

[] > should-not-pass
  42 > @

[] > once-upon-a-time
  42 > @

[] > forgets-everything
  42 > @

[] > must-do-better
  42 > @

[] > is-totally-broken
  42 > @

[] > was-a-trap
  42 > @

[] > hope-it-works
  42 > @

[] > dont-look-here
  42 > @

[] > never-saw-it-coming
  42 > @

[] > this-time-for-sure
  42 > @

[] > looks-fine-to-me
  42 > @

[] > there-it-goes
  42 > @

[] > it-is-fine-probably
  42 > @

[] > returns-something-strange
  42 > @

[] > maybe-next-time
  42 > @

[] > disappears-silently
  42 > @

[] > follows-the-rules
  42 > @

[] > well-this-is-awkward
  42 > @

[] > is-never-called
  42 > @

[] > why-this-again
  42 > @

[] > finds-nothing-at-all
  42 > @

[] > sounds-legit
  42 > @

[] > here-we-go-again
  42 > @

[] > it-was-working-before
  42 > @

[] > expected-the-unexpected
  42 > @

[] > it-seems-fine
  42 > @

[] > suddenly-works
  42 > @

[] > too-late-now
  42 > @

[] > could-not-care-less
  42 > @

[] > oops-try-again
  42 > @

[] > it-just-works
  42 > @

[] > dont-push-that-button
  42 > @

[] > error-404-not-found
  42 > @

[] > is-kind-of-slow
  42 > @

[] > sleeps-forever
  42 > @

[] > who-did-this
  42 > @

[] > makes-zero-sense
  42 > @

[] > please-reboot
  42 > @

[] > it-has-a-plan
  42 > @

[] > will-never-finish
  42 > @

[] > accidentally-passed
  42 > @

[] > runs-in-circles
  42 > @

[] > i-think-its-ok
  42 > @

```

2024-12-09 08:22 UTC, volodya-lombrozo commented on src/test/java/org/eolang/lints/misc/TestObjectIsVerbInSingularTest.java
> + * @todo #72:90min Cache POS model after it's first load.
@h1alexbel We also might put the model right inside the plugin, it has 4MB size (which isn't so dramatically large.) What do you think? However, I'm not sure about license issues in this case.

2024-12-09 15:43 UTC, h1alexbel commented on src/test/java/org/eolang/lints/misc/TestObjectIsVerbInSingularTest.java
> + * @todo #72:90min Cache POS model after it's first load.
@volodya-lombrozo agree

2024-12-09 15:44 UTC, h1alexbel commented on src/test/java/org/eolang/lints/misc/TestObjectIsVerbInSingularTest.java
> + * @todo #72:90min Cache POS model after it's first load.
@volodya-lombrozo agree

2024-12-09 19:26 UTC, h1alexbel commented
@volodya-lombrozo updated pull request. Take a look again, please

2024-12-10 06:37 UTC, yegor256 commented
@h1alexbel it's not a good idea to keep binary files in Git repository, especially if these files are not ours. Instead, we can configure Maven to download the file during the build and place into the JAR.

2024-12-10 06:49 UTC, volodya-lombrozo reviewed
@h1alexbel Let's [remove the binary](https://github.com/objectionary/lints/pull/103#issuecomment-2530570646) then and create a separate puzzle (as you did it before). Then we will decide what to do with it later. All the rest looks good to me. Thank you.

2024-12-10 07:13 UTC, h1alexbel commented
@volodya-lombrozo updated. Take a look again, please

2024-12-10 07:48 UTC, volodya-lombrozo approved these changes
@h1alexbel Looks good to me, thank you

2024-12-10 07:59 UTC, h1alexbel commented
@yegor256 could we merge this one?

2024-12-10 08:03 UTC, yegor256 commented on src/main/java/org/eolang/lints/Program.java
> +        try {
@h1alexbel this is not a good idea in general to use static code blocks, because they are not testable at all: you can't create a unit test for this pice of code. A better design would be to create a new class `ProgramLints` and use it like this:

```
private static Iterable<Lint<XML>> lints = new ProgramLints().discover();
```

This is a perfectly testable design.

2024-12-10 08:08 UTC, yegor256 requested changes
@h1alexbel looks good, see a few comments above

2024-12-10 08:08 UTC, yegor256 commented on src/main/java/org/eolang/lints/misc/TestObjectIsVerbInSingular.java
> +@SuppressWarnings("PMD.TestClassWithoutTestCases")
@h1alexbel better rename the class, to something like `UnitTestWithoutVerb`

2024-12-10 08:08 UTC, yegor256 commented on src/main/java/org/eolang/lints/misc/TestObjectIsVerbInSingular.java
> +@SuppressWarnings("PMD.TestClassWithoutTestCases")
@h1alexbel or better make it exactly the same as the `check` of the `Defect` that you return: `UnitTestIsNotVerb` (`unit-test-is-not-verb`)

2024-12-10 08:26 UTC, h1alexbel commented
@yegor256 updated. Take a look, please

2024-12-10 08:40 UTC, yegor256 commented
@rultor merge

2024-12-10 08:42 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/45807-2530821134).

2024-12-10 08:48 UTC, merged

2024-12-10 08:48 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/45807-2530821134) (took me 5min).