feat(#51): incorrect-jvm-rt-location, incorrect-node-rt-location lints
objectionary/lints pull request #116
Opened 2024-12-08 11:24 UTC by h1alexbel

In this pull I've introduced two new lints: `incorrect-jvm-rt-location`, and `incorrect-node-rt-location` that checks the formatting of runtime locations for JVM and NodeJS respectively.

closes #51
History:
- **feat(#51): incorrect-jvm-rt**
- **feat(#51): incorrect-jvm-rt-location motive**
- **feat(#51): groupId:artifactId:version**
- **feat(#51): simpler**
- **feat(#51): incorrect-node-rt-location**

2024-12-08 11:27 UTC, h1alexbel commented
@yegor256 take a look, please

2024-12-08 11:34 UTC, yegor256 commented
@maxonfjvipon please, check this one

2024-12-08 13:09 UTC, maxonfjvipon requested changes

2024-12-08 13:09 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/metas/incorrect-jvm-rt-location.xsl
> +        <xsl:if test="$meta-head='rt' and count(part) &gt; 1 and $runtime='jvm' and not(matches($location, '^([a-zA-Z0-9_.-]+):([a-zA-Z0-9_.-]+):([0-9_.-]+)$'))">
@h1alexbel let's make this part `([0-9_.-]+)` stricter because it should validate semver which may contain only 3 numbers separated with dot

2024-12-08 13:09 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/metas/incorrect-node-rt-location.xsl
> +        <xsl:if test="$meta-head='rt' and count(part) &gt; 1 and $runtime='node' and not(matches($location, '^([a-zA-Z0-9_.-]+):([0-9_.-]+)$'))">
@h1alexbel let's make this part `([0-9_.-]+)` stricter because it should validate semver which may contain only 3 numbers separated with dot

2024-12-08 15:44 UTC, h1alexbel commented
@maxonfjvipon updated pull request. Take a look again, please

2024-12-08 20:51 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/metas/incorrect-jvm-rt-location.xsl
> +      <xsl:for-each select="/program/metas/meta">
@h1alexbel maybe we could move the conditions `$meta-head='rt'` and `count(part) &gt; 1` to `for-each`:
`<xsl:for-each select="/program/metas/meta[head/text()='rt' and count(part) &gt; 1]">`
There'll be less cycle iterations and the final `if` condition will be less verbose. WDYT?

2024-12-08 20:52 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/metas/incorrect-node-rt-location.xsl
> +      <xsl:for-each select="/program/metas/meta">
@h1alexbel same as [here](https://github.com/objectionary/lints/pull/116/files#r1875042033)

2024-12-08 20:53 UTC, maxonfjvipon reviewed
@h1alexbel looks good in general, but I would simplify the final `if` condition by moving some parts of it to `for-each`. See the comment above

2024-12-09 08:38 UTC, h1alexbel commented
@maxonfjvipon updated pull request. Take a look again, please

2024-12-09 09:10 UTC, maxonfjvipon approved these changes
@h1alexbel LGTM

2024-12-09 09:36 UTC, h1alexbel commented
@yegor256 can we merge this one>

2024-12-09 11:04 UTC, yegor256 commented
@rultor merge

2024-12-09 11:06 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/45793-2527605696).

2024-12-09 11:11 UTC, merged

2024-12-09 11:12 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/45793-2527605696) (took me 4min).