feat(#129): StanfordNLP in UnitTestIsNotVerb lint
objectionary/lints pull request #131
Opened 2024-12-10 19:22 UTC by h1alexbel

In this pull request I've replaced `opennlp` with `stanford-corenlp` library, and made `UnitTestIsNotVerb` lint stricter by allowing only `VBZ` (Verb, 3rd person singular present) verbs in the test names.

closes #129

2024-12-10 19:25 UTC, h1alexbel commented
@volodya-lombrozo please check this one

2024-12-11 06:48 UTC, yegor256 commented on src/main/java/org/eolang/lints/misc/UnitTestIsNotVerb.java
> +            );
@h1alexbel something is wrong with this formatting. Try this instead:

```
final CoreDocument doc = new CoreDocument(
  Stream
    .concat(
      Stream.of("It"),
      Arrays.stream(UnitTestIsNotVerb.KEBAB.split(name))
    )
    .map(s -> s.toLowerCase(Locale.ROOT))
    .collect(Collectors.joining(" "))
);
```

Make sure dots are vertically aligned. Also, read this: https://www.yegor256.com/2014/10/23/paired-brackets-notation.html

2024-12-11 08:04 UTC, volodya-lombrozo requested changes
@h1alexbel looks good, to be honest. One more advantage over `opennlp` is that we don't need to manage model downloading and cache management. It's awesome. However, I would add a `javadoc` comment to the `UnitTestsIsNotVerb.java` to explain why we are using this specific model instead of `opennlp` - you could also include links to the issues that prompted this choice.

Also, there is a significant concern regarding the size of these models. While `opennlp` has a size ~ `4M`, the `stanford-corenlp-4.5.7-models.jar` is `452M` which might pose a problem in some cases. For now It is worth mentioning this in the docs.

2024-12-11 11:20 UTC, h1alexbel commented
@volodya-lombrozo updated. Take a look, please

2024-12-11 11:25 UTC, volodya-lombrozo approved these changes
@h1alexbel Looks good to me, thank you for the contribution!

2024-12-11 11:27 UTC, h1alexbel commented
@yegor256 take a look, please

2024-12-11 12:27 UTC, yegor256 commented
@rultor merge

2024-12-11 12:30 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/45840-2535857022).

2024-12-11 12:37 UTC, merged

2024-12-11 12:38 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/45840-2535857022) (took me 6min).

2024-12-11 12:59 UTC, yegor256 commented
@h1alexbel thanks!