feat(#133): Add `MeasuredXsl` And Tweak `line-is-absent` Check
objectionary/lints pull request #147
Opened 2024-12-13 15:39 UTC by volodya-lombrozo

In this PR I've:

1) Added `MeasuredXsl` that can measure time of all `xsl` transformations and prints messages into a log:
```
18:35:05 [WARN] org.eolang.lints.MeasuredXsl: XSL transformation 'sparse-decoration' took 473ms, whereas threshold is 100ms
```

2) I tweaked `line-is-absent` check:

From `ProgramTest#lintsLargeJnaClass(@Mktmp final Path home)`:

Before:
```
org.eolang.lints.MeasuredXSL: XSL transformation 'line-is-absent' took 4s, whereas threshold is 100ms
```
After:
```
17:51:22 [WARN] org.eolang.lints.MeasuredXSL: XSL transformation 'line-is-absent' took 117ms, whereas threshold is 100ms
```

___

Benchmark

Before:

```
Input: com/sun/jna/Pointer.class
Size of .class: 22Kb (22Kb bytes)
Size of .xmir after disassemble: 1Mb (1Mb bytes, 29630 lines)
Lint time: 9s (9332 ms)
```

After:

```
Input: com/sun/jna/Pointer.class
Size of .class: 22Kb (22Kb bytes)
Size of .xmir after disassemble: 1Mb (1Mb bytes, 29630 lines)
Lint time: 7s (7200 ms)
```

Realted to #133.

2024-12-13 15:40 UTC, volodya-lombrozo commented
@yegor256 Could you have a look, please?

2024-12-13 16:42 UTC, yegor256 commented on src/main/java/org/eolang/lints/MeasuredXsl.java
> +public final class MeasuredXsl implements XSL {
@volodya-lombrozo maybe it's better to put it into `test/` directory? It's only for tests, right?

2024-12-15 06:04 UTC, volodya-lombrozo commented on src/main/java/org/eolang/lints/MeasuredXsl.java
> +public final class MeasuredXsl implements XSL {
@yegor256 I can't place it into `test/` directory, since I use in in `LintByXsl` class.

2024-12-15 07:42 UTC, yegor256 commented on src/main/java/org/eolang/lints/MeasuredXsl.java
> +public final class MeasuredXsl implements XSL {
@volodya-lombrozo let's make it package private then

2024-12-15 10:39 UTC, yegor256 requested changes
@volodya-lombrozo let's make this class package-private, since it's not part of external API of this library

2024-12-16 08:30 UTC, yegor256 commented
@rultor merge

2024-12-16 08:33 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/45913-2544911420).

2024-12-16 08:39 UTC, merged

2024-12-16 08:39 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/45913-2544911420) (took me 5min).

2024-12-16 08:51 UTC, yegor256 commented
@volodya-lombrozo thanks!