feat(#67): object-has-data lint
objectionary/lints pull request #152
Opened 2024-12-16 15:11 UTC by h1alexbel

In this pull I've added new lint: `object-has-data`, that ensures that only object, based on `org.eolang.bytes` contain the data, otherwise issues `critical` defect.

closes #67
History:
- **feat(#67): data-is-not-in-bytes-object**
- **feat(#67): rename -> object-has-data**
- **feat(#67): passes**

2024-12-16 15:18 UTC, h1alexbel commented
@maxonfjvipon please check

2024-12-16 15:30 UTC, maxonfjvipon requested changes

2024-12-16 15:30 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/critical/object-has-data.xsl
> +      <xsl:apply-templates select="//o" mode="with-data"/>
@h1alexbel let's improve a bit this xpath: `o[@base and @base!='org.eolang.bytes']`. This will help to xslt engine to find relevant objects faster. Also please check `eo-parser`, maybe also just `bytes` should be allowed for `@base` attribute, because we can get just `bytes` after parsing

2024-12-16 15:30 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/critical/object-has-data.xsl
> +    <xsl:if test="$bytes != '' and not(@base = 'org.eolang.bytes')">
@h1alexbel we can remove the condition `not(@base='org.eolang.bytes')`, see the comment above

2024-12-16 15:38 UTC, h1alexbel commented on src/main/resources/org/eolang/lints/critical/object-has-data.xsl
> +      <xsl:apply-templates select="//o" mode="with-data"/>
@maxonfjvipon found this one: https://github.com/objectionary/eo/blob/8ddedba1837ca97f0fb24dfa37cfc008ee6209ed/eo-parser/src/main/resources/org/eolang/parser/add-refs.xsl#L35

It looks like `bytes` are also valid, right?

2024-12-17 04:34 UTC, yegor256 commented on src/main/resources/org/eolang/lints/critical/object-has-data.xsl
> +      <xsl:text>The only org.eolang.bytes object may have the data</xsl:text>
@h1alexbel we can say better:

```
Only objects with their @base attributes containing 'org.eolang.bytes' may contain data, while this object contains '...'
```

Or

```
Only objects with their @base attributes containing 'org.eolang.bytes' may contain data, while this object doesn't have @base attribute at all
```

Depending on the situation.

2024-12-17 04:35 UTC, yegor256 commented on src/main/resources/org/eolang/motives/critical/object-has-data.md
> +Each object `</o>` in [XMIR] must not have the data, unless it's base is
@h1alexbel it's `<o/>`, not `</o>`

2024-12-17 04:35 UTC, yegor256 commented on src/test/resources/org/eolang/lints/packs/object-has-data/catches-data-in-objects.yaml
> +      <o name="foo">
@h1alexbel what is the point of having identical test cases? They are not different, don't help us test any specific problems, just making noise, IMHO

2024-12-17 04:36 UTC, yegor256 commented on src/test/resources/org/eolang/lints/packs/object-has-data/catches-data-in-objects.yaml
> +      <o name="bar">
@h1alexbel also, it's better to have separate YAML files for separate test scenarios, instead of grouping cases in one YAML

2024-12-17 07:30 UTC, h1alexbel commented
@yegor256 updated. Take a look, please

2024-12-17 07:40 UTC, yegor256 commented
@maxonfjvipon LGTM, what do you think?

2024-12-17 09:41 UTC, maxonfjvipon approved these changes
@h1alexbel LGTM

2024-12-17 10:34 UTC, h1alexbel commented
@yegor256 could we merge this one?

2024-12-17 10:50 UTC, yegor256 commented
@rultor merge

2024-12-17 10:52 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/45946-2548130760).

2024-12-17 10:59 UTC, merged