feat(#110): object-does-not-match-filename lint
objectionary/lints pull request #163
Opened 2024-12-20 07:08 UTC by h1alexbel

In this pull I've implemented new lint: `object-does-not-match-filename`, that issues `warning` defect in case top object name is different from the filename.

closes #110 
History:
- **feat(#110): bad/good test cases**
- **feat(#110): object-does-not-match-filename**
- **feat(#110): move**
- **feat(#110): passes**
- **feat(#110): stronger XPaths**
- **feat(#110): passes with children**
- **feat(#110): allows good name with chidren**
- **feat(#110): ignore in tests**
- **feat(#110): program name**

2024-12-20 12:40 UTC, h1alexbel commented
@maxonfjvipon please check

2024-12-23 08:47 UTC, maxonfjvipon requested changes
@h1alexbel looks good, just one small change is required

2024-12-23 08:47 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/names/object-does-not-match-filename.xsl
> +      <xsl:apply-templates select="/program/objects/o[@name != $filename]" mode="with-data"/>
@h1alexbel I think mode `with-data` is confusing here, let's add some meaningful name to the mode

2024-12-23 09:16 UTC, h1alexbel commented
@maxonfjvipon updated. Take a look, please

2024-12-23 09:47 UTC, maxonfjvipon approved these changes
@h1alexbel looks good now, thanks!

2024-12-23 10:01 UTC, h1alexbel commented
@yegor256 take a look, please

2024-12-23 13:26 UTC, yegor256 approved these changes
@h1alexbel LGTM

2024-12-23 13:26 UTC, yegor256 commented
@rultor merge

2024-12-23 13:28 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/46056-2559709877).

2024-12-23 13:34 UTC, merged

2024-12-23 13:35 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/46056-2559709877) (took me 6min).