feat(#77): bytes-without-data lint
objectionary/lints pull request #171
Opened 2024-12-25 13:24 UTC by h1alexbel

In this pull I've introduced new lint: `bytes-without-data`, that issues `critical` defect in case of `<o/>` with base containing `org.eolang.bytes` (`bytes` for short) does not have text data inside.

closes #77

2024-12-25 13:26 UTC, h1alexbel commented
@maxonfjvipon please check

2024-12-25 15:45 UTC, maxonfjvipon commented
@h1alexbel let's wait for @yegor256 comment to [this](https://github.com/objectionary/lints/issues/77#issuecomment-2561933623)

2024-12-26 09:26 UTC, maxonfjvipon commented
@h1alexbel let's put on hold this PR until we fix XMIR so it correspond to EO

2025-01-07 19:21 UTC, maxonfjvipon commented
@h1alexbel not yet, I'll let you know

2025-04-10 11:21 UTC, h1alexbel commented
@maxonfjvipon updated. Take a look, please

2025-04-13 08:55 UTC, h1alexbel commented
@maxonfjvipon reminder

2025-04-14 07:48 UTC, h1alexbel commented
@maxonfjvipon reminder

2025-04-14 10:45 UTC, maxonfjvipon requested changes

2025-04-14 10:45 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/critical/bytes-without-data.xsl
> +      <xsl:apply-templates select="//o[not(eo:has-data(.)) and parent::o[@base='Q.org.eolang.bytes']]" mode="with-data"/>
@h1alexbel maybe let's add `and eo:abstract(.)`?

2025-04-14 12:30 UTC, h1alexbel commented
@maxonfjvipon updated. Take a look, please

2025-04-14 13:27 UTC, maxonfjvipon approved these changes

2025-04-14 13:35 UTC, h1alexbel commented
@yegor256 take a look, please

2025-04-15 07:32 UTC, h1alexbel commented
@yegor256 reminder

2025-04-15 07:37 UTC, rultor commented
> @rultor merge

@yegor256 OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/47887-2804107634).

2025-04-15 07:54 UTC, merged

2025-04-15 07:55 UTC, rultor commented
> @rultor merge

@yegor256 Done! FYI, the full log is [here](https://www.rultor.com/t/47887-2804107634) (took me 17min).