feat(#46): atom-with-data lint
objectionary/lints pull request #172
Opened 2024-12-25 14:13 UTC by h1alexbel

In this pull I've introduced new lint: `atom-with-data`, that issues `critical` defect in case atom has data inside.

closes #46

2024-12-25 14:18 UTC, h1alexbel commented
@maxonfjvipon please check

2024-12-25 15:43 UTC, maxonfjvipon requested changes

2024-12-25 15:43 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/critical/atom-with-data.xsl
> +      <xsl:apply-templates select="//o[@atom]" mode="with-data"/>
@h1alexbel let's rename mode to `atom` here, it seems more appropriate

2024-12-25 16:02 UTC, h1alexbel commented
@maxonfjvipon updated. Take a look, please

2024-12-26 09:06 UTC, maxonfjvipon approved these changes

2024-12-26 09:20 UTC, h1alexbel commented
@yegor256 please check

2024-12-26 09:29 UTC, yegor256 approved these changes
ok

2024-12-26 09:29 UTC, merged

2024-12-26 09:29 UTC, yegor256 commented
@h1alexbel thanks!

2024-12-26 16:59 UTC, 0crat commented
@h1alexbel Thanks for the contribution! You've earned +9 points for this: +4 as a basis; +8 for the 174 hits-of-code that you wrote; -4 for very few (4) comments. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+7](https://www.eolang.org/zerocracy/objectionary-vitals.html).

2024-12-26 16:59 UTC, 0crat commented
@yegor256 Thanks for the review! You've earned +4 points for this: +4 as a basis; -10 for very few (5) comments; +10 to give you at least something.  Your running balance is [-4](https://www.eolang.org/zerocracy/objectionary-vitals.html).

2024-12-26 16:59 UTC, 0crat commented
@maxonfjvipon Thanks for the review! You've earned +4 points for this: +4 as a basis; -10 for very few (5) comments; +10 to give you at least something.  Your running balance is [+16](https://www.eolang.org/zerocracy/objectionary-vitals.html).