feat(#23): architect-duplicate-lint
objectionary/lints pull request #177
Opened 2024-12-26 18:12 UTC by h1alexbel

In this pull I've implemented new lint: `architect-duplicate`, that ensures that only one `+architect` meta is in use.

closes #23

2024-12-27 07:58 UTC, maxonfjvipon requested changes

2024-12-27 07:58 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/metas/architect-duplicate.xsl
> +            <xsl:text>0</xsl:text>
@h1alexbel let's put here the last architect meta line

2024-12-27 12:26 UTC, h1alexbel commented
@maxonfjvipon updated. Take a look, please

2024-12-30 08:15 UTC, h1alexbel commented
@maxonfjvipon reminder

2024-12-30 08:25 UTC, maxonfjvipon approved these changes

2024-12-30 08:55 UTC, h1alexbel commented
@yegor256 take a look, please

2024-12-30 09:03 UTC, merged

2024-12-30 09:03 UTC, yegor256 commented
@h1alexbel thanks!