feat(#49): package-without-tail lint
objectionary/lints pull request #178
Opened 2024-12-26 18:59 UTC by h1alexbel

In this pull, I've introduced new lint: `package-without-tail` that issues `critical` defect if `+package` meta is used without a tail.

closes #49

2024-12-26 19:04 UTC, h1alexbel commented
@maxonfjvipon please check

2024-12-27 05:11 UTC, maxonfjvipon requested changes

2024-12-27 05:11 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/critical/package-without-tail.xsl
> +            <xsl:text>0</xsl:text>
@h1alexbel is there a way we can put a real line number where `package` meta is located? Please check [this](https://github.com/objectionary/eo/blob/master/eo-parser/src/main/java/org/eolang/parser/XeEoListener.java) file at the line 151 we add line to meta. Let's use it?

2024-12-27 07:08 UTC, h1alexbel commented
@maxonfjvipon updated. Take a look, please

2024-12-27 07:57 UTC, maxonfjvipon approved these changes

2024-12-27 08:04 UTC, h1alexbel commented
@yegor256 take a look, please

2024-12-27 14:10 UTC, merged

2024-12-27 14:10 UTC, yegor256 commented
@h1alexbel thanks!

2024-12-28 12:22 UTC, 0crat commented
@h1alexbel Thanks for the contribution! You've earned +4 points for this: +4 as a basis; +6 for the 123 hits-of-code that you wrote; -16 for the lack of code review; -4 for very few (4) comments; +14 to give you at least something. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+16](https://www.eolang.org/zerocracy/objectionary-vitals.html).