fix(#176): set line to '0' in `empty-object` if `@line` is weird
objectionary/lints pull request #181
Opened 2024-12-27 12:02 UTC by h1alexbel

In this pull request I fixed line number reporting in `empty-object` lint, in cases when line number is NaN.
- **fix(#176): tests**
- **fix(#176): line 0 if NaN**

2024-12-27 12:07 UTC, h1alexbel commented
@maxonfjvipon please check

2024-12-27 19:57 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/errors/empty-object.xsl
> +            <xsl:value-of select="if (@line and not(number(@line) = NaN) and number(@line) = number(@line)) then @line else '0'"/>
@h1alexbel as far as I know `NaN = NaN `is `false`, so if you checked that line is not `NaN`, what this `line = line` extra comparison for?

2024-12-28 09:45 UTC, h1alexbel commented
@maxonfjvipon updated. Take a look, please

2024-12-28 11:21 UTC, maxonfjvipon approved these changes

2024-12-28 11:30 UTC, h1alexbel commented
@yegor256 take a look, please

2024-12-28 12:10 UTC, yegor256 requested changes
@h1alexbel thanks! see one comment above

2024-12-28 12:10 UTC, yegor256 commented on src/main/resources/org/eolang/lints/errors/empty-object.xsl
> +            <xsl:value-of select="if (@line and number(@line) = number(@line)) then @line else '0'"/>
@h1alexbel why do we check it only in this XSL? If this problem is external, we should be careful with the `@line` attribute in all XSL stylesheets. Maybe let's introduce a function `eo:lineno(x)`, which will do what you do here, but used in all XSLs?

2024-12-29 10:26 UTC, h1alexbel commented
@yegor256 updated. Take a look, please

2024-12-29 10:31 UTC, yegor256 commented
@h1alexbel since you introduced this new function, maybe it's reasonable to use it in all XSLs? Also, no need to start the name of this XSL with underscore. It was done in EO repository in order to exclude this XSL from test pack.

2024-12-29 11:24 UTC, h1alexbel commented
@yegor256 updated. Take a look, please

2024-12-29 12:51 UTC, yegor256 approved these changes
@h1alexbel perfect!

2024-12-29 12:51 UTC, merged