feat(#144): Each Lint timings in benchmark
objectionary/lints pull request #184
Opened 2024-12-29 12:32 UTC by h1alexbel

In this pull I've added `BcProgram` for measuring each lint timings for XMIR-generated program during the benchmark.

closes #144
History:
- **feat(#144): timings**
- **feat(#144): typo**
- **feat(#144): Lint#name()**
- **feat(#144): present timings.csv**

2024-12-29 12:40 UTC, h1alexbel commented
@volodya-lombrozo could you review this one?

2024-12-30 07:40 UTC, volodya-lombrozo requested changes
@h1alexbel Thank you for the contribution! Just several suggestions.

2024-12-30 07:40 UTC, volodya-lombrozo commented on pom.xml
> +      <groupId>com.opencsv</groupId>
@h1alexbel Do we really need these libraries? At least I haven't found any usage of `com.opencsv`. Maybe I missing something?

2024-12-30 07:40 UTC, volodya-lombrozo commented on src/test/java/org/eolang/lints/ProgramTest.java
> +    final class BcProgram {
@h1alexbel Can we make this class `private static`?  Or we exact this visibility level for `BcProgram`?

2024-12-30 07:40 UTC, volodya-lombrozo commented on src/test/java/org/eolang/lints/ProgramTest.java
> +        public Collection<Defect> defects() {
@h1alexbel This is code duplication with the `Program` class. If we change `Program` implementation, `BcProgram` won't "see" these changes. It's better to rely on the existing `Program` implementation instead. I guess you can achieve this by implementing `LtMeasured`, or something similar. I'm not insisting on a concrete implementation, but it's better to remove this code duplication - at least in a separate issue. 
What do you think?

2024-12-30 07:40 UTC, volodya-lombrozo commented on pom.xml
> +      <groupId>com.opencsv</groupId>
@h1alexbel Maybe, since you are using these libraries in tests only, it's better to add the `test` scope to them?

2024-12-30 08:05 UTC, h1alexbel commented on pom.xml
> +      <groupId>com.opencsv</groupId>
@volodya-lombrozo `com.opencsv` is required for `MnCsv` class from `tojos`

2024-12-30 08:07 UTC, h1alexbel commented on src/test/java/org/eolang/lints/ProgramTest.java
> +        public Collection<Defect> defects() {
@volodya-lombrozo I'm not sure about the best way to do it for now. How about creating a new puzzle?

2024-12-30 08:15 UTC, h1alexbel commented
@volodya-lombrozo updated. Take a look, please

2024-12-31 06:07 UTC, volodya-lombrozo approved these changes
@h1alexbel Looks good to me, thank you!
@yegor256 Could you merge that changes, please?

2024-12-31 06:40 UTC, merged

2024-12-31 06:40 UTC, yegor256 commented
@h1alexbel @volodya-lombrozo thanks!