feat(#62): atom-with-phi lint
objectionary/lints pull request #187
Opened 2024-12-30 13:21 UTC by h1alexbel

In this pull I've implemented new lint: `atom-with-phi`, that issues `critical` defect in case atom has `@` (`φ`) attribute

closes #62

2024-12-30 13:24 UTC, h1alexbel commented
@maxonfjvipon please check

2024-12-30 18:11 UTC, maxonfjvipon requested changes

2024-12-30 18:11 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/critical/atom-with-phi.xsl
> +      <xsl:apply-templates select="//o[@atom][.//o[@name='@']]" mode="with-phi"/>
@h1alexbel I think this xpath can be simplified to `//o[@atom and o[@name='@']]`

2024-12-30 18:11 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/critical/atom-with-phi.xsl
> +      <xsl:text>Atoms must not have '@' attribute "</xsl:text>
@h1alexbel let's clarify here that atom must not have *void* '@' attribute

2024-12-30 18:13 UTC, h1alexbel commented on src/main/resources/org/eolang/lints/critical/atom-with-phi.xsl
> +      <xsl:text>Atoms must not have '@' attribute "</xsl:text>
@maxonfjvipon so, it should be `Atom` instead of `Atoms`, right?

2024-12-30 18:19 UTC, maxonfjvipon commented on src/main/resources/org/eolang/lints/critical/atom-with-phi.xsl
> +      <xsl:text>Atoms must not have '@' attribute "</xsl:text>
@h1alexbel no, 'atoms' is ok, '@' attribute should be VOID

2024-12-30 18:27 UTC, h1alexbel commented
@maxonfjvipon updated. Take a look, please

2024-12-30 18:28 UTC, maxonfjvipon approved these changes

2024-12-30 19:22 UTC, yegor256 commented on src/main/resources/org/eolang/lints/critical/atom-with-phi.xsl
> +      <xsl:text>Atoms must not have void '@' attribute "</xsl:text>
@h1alexbel typo in the end?

2024-12-30 19:26 UTC, h1alexbel commented on src/main/resources/org/eolang/lints/critical/atom-with-phi.xsl
> +      <xsl:text>Atoms must not have void '@' attribute "</xsl:text>
@yegor256 yes, fixed

2024-12-30 19:29 UTC, h1alexbel commented
@yegor256 updated, take a look again, please

2024-12-31 06:40 UTC, merged

2024-12-31 06:40 UTC, yegor256 commented
@h1alexbel thanks!