feat(#149): incorrect-alias lint
objectionary/lints pull request #188
Opened 2024-12-30 14:53 UTC by h1alexbel

In this pull I've introduced new lint: `incorrect-alias`, that issues critical defect in case `+alias` meta pointing to the non existing file.

closes #149
History:
- **feat(#149): incorrect-alias**
- **feat(#149): no empty**
- **feat(#149): passes if not aliases**
- **feat(#149): ignores absence of package**
- **feat(#149): motive**
- **feat(#149): passes if file is found**

2024-12-30 15:23 UTC, h1alexbel commented
@yegor256 please check

2024-12-30 17:26 UTC, yegor256 commented
@h1alexbel looks like a great start! However, I believe that this lint must implement `Lint<Map<String, XML>>` (similar to how `LtUnitTestMissing` does). The presence of "files" must be checked in the provided `Map`, not on disc.

2024-12-31 10:06 UTC, h1alexbel commented
@yegor256 updated. Take a look, please

2024-12-31 10:16 UTC, h1alexbel commented
@yegor256 updated. Take a look, please

2024-12-31 11:37 UTC, h1alexbel commented
@yegor256 ready for review

2024-12-31 12:29 UTC, yegor256 requested changes
@h1alexbel looks very good now! A few small comments above.

2024-12-31 12:29 UTC, yegor256 commented on src/main/java/org/eolang/lints/critical/LtIncorrectAlias.java
> +                    if (!"1".equals(xmir.xpath("count(//meta[head='package'])").get(0))) {
@h1alexbel You can do it simpler:

```
if (xmir.nodes("//meta[head='package']").size() != 1) {
```

2024-12-31 12:29 UTC, yegor256 commented on src/main/java/org/eolang/lints/critical/LtIncorrectAlias.java
> +                for (final XML alias : xmir.nodes("//meta[head='alias']/tail")) {
@h1alexbel it's better to avoid `//` at the beginning of XPath expressions, because such requests are rather slow (we have to search the entire document). Better write this one like this: `/program/metas/meta[head='alias']/tail`

2024-12-31 13:14 UTC, h1alexbel commented
@yegor256 updated. Take a look, please

2024-12-31 14:04 UTC, merged

2024-12-31 14:04 UTC, yegor256 commented
@h1alexbel thanks!